In [236]:
sales_data = """
OrderID,CustomerID,Product,Quantity,Price,ShippingDate,Discount
1,101,Laptop,1,1200,2025-01-05,0.1
2,102,Mouse,2,25,2025-01-06,0.05
3,101,,1,250,2025-01-07,0.1
4,103,Keyboard,1,75,2025-01-08,0
5,104,Laptop,1,1200,2025-01-09,0.1
6,105,Mouse,3,25,2025-01-10,0
7,102,Monitor,1,,2025-01-11,0.05
8,101,Laptop,2,1200,2025-01-12,0.15
9,103,Keyboard,2,75,2025-01-13,0.1
10,,Mouse,1,25,2025-01-14,0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as py
from io import StringIO

In [237]:
### Load data and initial inspection

In [238]:
sales_df = pd.read_csv(StringIO(sales_data), parse_dates=['ShippingDate'])

# top 5
sales_df

   OrderID  CustomerID   Product  Quantity   Price ShippingDate  Discount
0        1       101.0    Laptop         1  1200.0   2025-01-05      0.10
1        2       102.0     Mouse         2    25.0   2025-01-06      0.05
2        3       101.0       NaN         1   250.0   2025-01-07      0.10
3        4       103.0  Keyboard         1    75.0   2025-01-08      0.00
4        5       104.0    Laptop         1  1200.0   2025-01-09      0.10
5        6       105.0     Mouse         3    25.0   2025-01-10      0.00
6        7       102.0   Monitor         1     NaN   2025-01-11      0.05
7        8       101.0    Laptop         2  1200.0   2025-01-12      0.15
8        9       103.0  Keyboard         2    75.0   2025-01-13      0.10
9       10         NaN     Mouse         1    25.0   2025-01-14      0.00

In [239]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       10 non-null     int64
 1   CustomerID    9 non-null      float64
 2   Product       9 non-null      object
 3   Quantity      10 non-null     int64
 4   Price         9 non-null      float64
 5   ShippingDate  10 non-null     datetime64[ns]
 6   Discount      10 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(1)
memory usage: 692.0+ bytes

In [240]:
sales_df.describe()

,OrderID,CustomerID,Quantity,Price,ShippingDate,Discount
count,10.00000,9.000000,10.000000,9.000000,10,10.000000
mean,5.50000,102.444444,1.500000,452.777778,2025-01-09 12:00:00,0.065000
min,1.00000,101.000000,1.000000,25.000000,2025-01-05 00:00:00,0.000000
25%,3.25000,101.000000,1.000000,25.000000,2025-01-07 06:00:00,0.012500
50%,5.50000,102.000000,1.000000,75.000000,2025-01-09 12:00:00,0.075000
75%,7.75000,103.000000,2.000000,1200.000000,2025-01-11 18:00:00,0.100000
max,10.00000,105.000000,3.000000,1200.000000,2025-01-14 00:00:00,0.150000
std,3.02765,1.424001,0.707107,564.640987,NaN,0.052967

In [241]:
sales_df.shape

#10 rows 7 columns

(10, 7)

In [242]:
# Handle missing values
# show only rows where the customer id is missing
# 
sales_df['Product'].isnull().sum()

sales_df[sales_df['Product'].isna()]

   OrderID  CustomerID Product  Quantity  Price ShippingDate  Discount
2        3       101.0     NaN         1  250.0   2025-01-07       0.1

In [243]:
# order id 3 = product = monitor



sales_df.loc[3, "Product"] = 'monitor'

# order id 7 price = 250

sales_df.loc[7, "Price"] = 250

sales_df

# convert all products to lowercase 
sales_df['revenue'] = sales_df['Price']* sales_df['Quantity']

sales_df['Product'] = sales_df['Product'].str.strip().str.lower()

# monitor sales

monitor_sales = sales_df.groupby('Product')['revenue'].sum()['monitor']

monitor_sales

75.0

In [244]:
customers_df = pd.DataFrame({
    'CustomerID': [101, 102, 103, 104, 105, 106, 107],
    'CustomerName': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'East', 'South']
})

merged_data = pd.merge(sales_df, customers_df, on='CustomerID', how="left")


merged_data['Region'] = merged_data['Region'].str.strip().str.upper()

merged_data

merged_data['Revenue_dble'] = merged_data['revenue'].apply(lambda x: x*2)
merged_data

merged_data['Region_lower'] = merged_data['Region'].astype(str).apply(lambda x: x.title()if isinstance(x, str) else x)
merged_data['Region_lower']

0    North
1    South
2    North
3     East
4     West
5    North
6    South
7    North
8     East
9      Nan
Name: Region_lower, dtype: object

In [245]:
import pandas as pd
import numpy as np

sales_df = pd.DataFrame({
    'OrderID': range(1, 11),
    'CustomerID': [101, 102, 101, 103, 104, 105, 102, 101, 103, 106],
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Laptop', 'Mouse', 'Monitor', 'Laptop', 'Keyboard', 'Mouse'],
    'Quantity': [1, 2, 1, 1, 1, 3, 1, 2, 2, 1],
    'Price': [1200, 25, 250, 75, 1200, 25, 250, 1200, 75, 25],
    'ShippingDate': pd.to_datetime(['2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08', '2025-01-09',
                                    '2025-01-10', '2025-01-11', '2025-01-12', '2025-01-13', '2025-01-14']),
    'Discount': [0.1, 0.05, 0.1, 0, 0.1, 0, 0.05, 0.15, 0.1, 0]
})

# Apply previous corrections
sales_df.loc[2, 'Product'] = 'Monitor'
sales_df.loc[6, 'Price'] = 250
sales_df['Product'] = sales_df['Product'].str.lower().str.strip()
sales_df['TotalRevenue'] = sales_df['Quantity'] * sales_df['Price']

# Let's adjust the indices to be cleaner for this round
sales_df = sales_df.set_index('OrderID')

print("--- Cleaned and Prepped DataFrame for this round ---")
print(sales_df)

--- Cleaned and Prepped DataFrame for this round ---
         CustomerID   Product  Quantity  Price ShippingDate  Discount  \
OrderID
1               101    laptop         1   1200   2025-01-05      0.10
2               102     mouse         2     25   2025-01-06      0.05
3               101   monitor         1    250   2025-01-07      0.10
4               103  keyboard         1     75   2025-01-08      0.00
5               104    laptop         1   1200   2025-01-09      0.10
6               105     mouse         3     25   2025-01-10      0.00
7               102   monitor         1    250   2025-01-11      0.05
8               101    laptop         2   1200   2025-01-12      0.15
9               103  keyboard         2     75   2025-01-13      0.10
10              106     mouse         1     25   2025-01-14      0.00

         TotalRevenue
OrderID
1                1200
2                  50
3                 250
4                  75
5                1200
6                  75
7                 250
8                2400
9                 150
10                 25

In [246]:
# units of each product ordered by each customer

order_stats = sales_df.groupby(['Product','CustomerID']).agg(
    no_units = ('Quantity','sum'),
    total_spend = ('TotalRevenue', 'sum'),
    orders_placed = ('CustomerID', 'count')


).reset_index().sort_values(by='total_spend', ascending=False)
order_stats

    Product  CustomerID  no_units  total_spend  orders_placed
1    laptop         101         3         3600              2
2    laptop         104         1         1200              1
3   monitor         101         1          250              1
4   monitor         102         1          250              1
0  keyboard         103         3          225              2
6     mouse         105         3           75              1
5     mouse         102         2           50              1
7     mouse         106         1           25              1

In [247]:
# convert stats to pivot

order_stats_pivot = order_stats.pivot_table(
    index="CustomerID",
    columns="Product",
    values="no_units",
    aggfunc="sum",
    fill_value=0
)

order_stats_pivot

Product     keyboard  laptop  monitor  mouse
CustomerID
101                0       3        1      0
102                0       0        1      2
103                3       0        0      0
104                0       1        0      0
105                0       0        0      3
106                0       0        0      1

In [248]:
# using a pivot table. best approach

customer_product_units = sales_df.pivot_table(
    index='CustomerID',
    columns='Product',
    values='Quantity',
    aggfunc='sum',
    fill_value=0
    
)
customer_product_units

Product     keyboard  laptop  monitor  mouse
CustomerID
101                0       3        1      0
102                0       0        1      2
103                3       0        0      0
104                0       1        0      0
105                0       0        0      3
106                0       0        0      1

In [249]:
# time series

sales_df

,CustomerID,Product,Quantity,Price,ShippingDate,Discount,TotalRevenue
OrderID,,,,,,,
1,101,laptop,1,1200,2025-01-05,0.10,1200
2,102,mouse,2,25,2025-01-06,0.05,50
3,101,monitor,1,250,2025-01-07,0.10,250
4,103,keyboard,1,75,2025-01-08,0.00,75
5,104,laptop,1,1200,2025-01-09,0.10,1200
6,105,mouse,3,25,2025-01-10,0.00,75
7,102,monitor,1,250,2025-01-11,0.05,250
8,101,laptop,2,1200,2025-01-12,0.15,2400
9,103,keyboard,2,75,2025-01-13,0.10,150
10,106,mouse,1,25,2025-01-14,0.00,25

In [250]:
sales_df

,CustomerID,Product,Quantity,Price,ShippingDate,Discount,TotalRevenue
OrderID,,,,,,,
1,101,laptop,1,1200,2025-01-05,0.10,1200
2,102,mouse,2,25,2025-01-06,0.05,50
3,101,monitor,1,250,2025-01-07,0.10,250
4,103,keyboard,1,75,2025-01-08,0.00,75
5,104,laptop,1,1200,2025-01-09,0.10,1200
6,105,mouse,3,25,2025-01-10,0.00,75
7,102,monitor,1,250,2025-01-11,0.05,250
8,101,laptop,2,1200,2025-01-12,0.15,2400
9,103,keyboard,2,75,2025-01-13,0.10,150
10,106,mouse,1,25,2025-01-14,0.00,25

In [251]:
weekly_ma = weekly_rev.rolling(window=1).mean()
weekly_ma

ShippingDate
2025-01-05    1200.0
2025-01-12    4300.0
2025-01-19     175.0
Freq: W-SUN, Name: TotalRevenue, dtype: float64

In [252]:
# categorical & descriptive statisics

# top 3 most popular products

pop_products_stats = sales_df.groupby('Product').agg(
    order_units=('Quantity','sum'),
    orders_placed=('CustomerID','count'),
    total_sales=('TotalRevenue', 'sum')
).reset_index().sort_values(by='order_units', ascending=False)

pop_products_stats

    Product  order_units  orders_placed  total_sales
3     mouse            6              3          150
1    laptop            4              3         4800
0  keyboard            3              2          225
2   monitor            2              2          500

In [253]:
top_3_products = sales_df['Product'].value_counts()
top_3_products

Product
laptop      3
mouse       3
monitor     2
keyboard    2
Name: count, dtype: int64

In [277]:
# products with high discount
disc_check=lambda x: 1 if x>=0.1 else 0
sales_df['HighDiscountFlag'] = sales_df['Discount'].apply(disc_check)
sales_df

# better alternative

sales_df['HighDiscountFlag2'] = np.where(sales_df['Discount']>=0.1, 1,0)
sales_df

sales_df['Price_Quartile'] = pd.qcut(sales_df['Price'], q=4, labels=['Low', 'Medium', 'High', 'Very High'])
sales_df.head()


sales_df['Price_Quartile_Manual'] = pd.cut(sales_df['Price'], bins=[0,400,600,800,1200], labels=['Low', 'Medium', 'High', 'Very High'] ) 
sales_df

,CustomerID,Product,Quantity,Price,ShippingDate,Discount,TotalRevenue,HighDiscountFlag,HighDiscountFlag2,Price_Quartile,Price_Quartile_Manual
OrderID,,,,,,,,,,,
1,101,laptop,1,1200,2025-01-05,0.10,1200,1,1,Very High,Very High
2,102,mouse,2,25,2025-01-06,0.05,50,0,0,Low,Low
3,101,monitor,1,250,2025-01-07,0.10,250,1,1,High,Low
4,103,keyboard,1,75,2025-01-08,0.00,75,0,0,Medium,Low
5,104,laptop,1,1200,2025-01-09,0.10,1200,1,1,Very High,Very High
6,105,mouse,3,25,2025-01-10,0.00,75,0,0,Low,Low
7,102,monitor,1,250,2025-01-11,0.05,250,0,0,High,Low
8,101,laptop,2,1200,2025-01-12,0.15,2400,1,1,Very High,Very High
9,103,keyboard,2,75,2025-01-13,0.10,150,1,1,Medium,Low
10,106,mouse,1,25,2025-01-14,0.00,25,0,0,Low,Low

In [ ]:
# average total revene for all customer

# Step 1: Calculate the total revenue for each customer
customer_total_revenue = sales_df.groupby('CustomerID')['TotalRevenue'].sum()

print("--- Total Revenue per Customer ---")
print(customer_total_revenue)
print("\n")

# Step 2: Calculate the average of those total revenues
average_customer_revenue = customer_total_revenue.mean()

print("--- Average Total Revenue per Customer ---")
print(f"${average_customer_revenue:.2f}")

--- Total Revenue per Customer ---
CustomerID
101    3850
102     300
103     225
104    1200
105      75
106      25
Name: TotalRevenue, dtype: int64


--- Average Total Revenue per Customer ---
$945.83

In [ ]:
# return only the last two rows and the first two columns

sales_df.iloc[-2:,:2]

              CustomerID   Product
ShippingDate
2025-01-13           103  keyboard
2025-01-14           106     mouse